In [1]:
import os
import sys
import pandas as pd
import numpy as np

In [2]:
response_path = "/Users/nick/Desktop/new_refract/refract/work/70/815d084b665feb30df9d9805a9b49c/az20_2.5.csv"
feature_path = "/Users/nick/Desktop/new_refract/data/features/processed_features/x-all.pkl"

# load feature_df
feature_df = pd.read_pickle(feature_path)

In [5]:
feature_index = feature_df.index.values

In [6]:
# are there any duplicate index values? 
feature_df.index.duplicated().sum()

3

In [7]:
# which ones
feature_df[feature_df.index.duplicated()]

,ONCLIN_Ovary_Fallopian_Tube,ONCLIN_Myeloid,ONCLIN_Bowel,ONCLIN_Skin,ONCLIN_Bladder_Urinary_Tract,ONCLIN_Lung,ONCLIN_Kidney,ONCLIN_Breast,ONCLIN_Lymphoid,ONCLIN_Pancreas,...,PROT_Q7Z3Q1-2,PROT_P03891,PROT_P03897,PROT_P22004,PROT_Q8IXQ9,PROT_Q9Y258,PROT_P20292,PROT_Q9H1C7,PROT_Q99735,PROT_Q9P003
ModelID,,,,,,,,,,,,,,,,,,,,,
ACH-000212,0,0,0,0,0,0,0,1,0,0,...,NaN,0.008059,-0.133179,NaN,NaN,NaN,NaN,-0.233901,-3.091568,1.215902
ACH-000680,0,0,1,0,0,0,0,0,0,0,...,1.504832,NaN,NaN,-0.575171,NaN,NaN,-0.264856,NaN,NaN,0.507847
ACH-000997,0,0,1,0,0,0,0,0,0,0,...,NaN,NaN,-1.759864,NaN,NaN,NaN,NaN,0.240372,NaN,0.067733

In [8]:
feature_df.loc["ACH-000212"]

,ONCLIN_Ovary_Fallopian_Tube,ONCLIN_Myeloid,ONCLIN_Bowel,ONCLIN_Skin,ONCLIN_Bladder_Urinary_Tract,ONCLIN_Lung,ONCLIN_Kidney,ONCLIN_Breast,ONCLIN_Lymphoid,ONCLIN_Pancreas,...,PROT_Q7Z3Q1-2,PROT_P03891,PROT_P03897,PROT_P22004,PROT_Q8IXQ9,PROT_Q9Y258,PROT_P20292,PROT_Q9H1C7,PROT_Q99735,PROT_Q9P003
ModelID,,,,,,,,,,,,,,,,,,,,,
ACH-000212,0,0,0,0,0,0,0,1,0,0,...,NaN,NaN,0.381077,NaN,NaN,NaN,NaN,-0.471480,-0.231417,0.422698
ACH-000212,0,0,0,0,0,0,0,1,0,0,...,NaN,0.008059,-0.133179,NaN,NaN,NaN,NaN,-0.233901,-3.091568,1.215902